name = "hand-tracker-meckman"
compatibility_date = "2024-11-10"

[env.production]
route = "handtracker.meckman.org/*"

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
headers = { "Content-Type" = "text/html; charset=utf-8" }

[[env.production.rules]]
type = "Text"  
globs = ["**/*.js"]
headers = { "Content-Type" = "application/javascript; charset=utf-8" }

[[env.production.rules]]
type = "Text"
globs = ["**/*.css"]
headers = { "Content-Type" = "text/css; charset=utf-8" }